config/routes.rb
Rails.application.routes.draw do
  devise_for :accounts
  resources :posts
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get "about" => "public#about", as: :about
  get "blog" => "public#blog", as: :blog
  get "contact" => "public#contact", as: :contact

  post "post/view" => "posts#save_post_view", as: :post_view

  root to: "public#homepage"
end

app/models/account.rb
class Account < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  validates_presence_of :title, :url
  has_many :posts

end

app/models/post.rb
class Post < ApplicationRecord
  validates :title, presence: true
  validates :summary, presence: true
  validates :body, presence: true

  belongs_to :category
  belongs_to :account

  # callbacks - validation / save / create /update / destroy
  after_create :update_total_posts_count

  scope :active, -> { where( active: true ) }
  scope :order_by_latest_first, -> { order( created_at: :desc ) }
  scope :limit_2, -> { limit( 2 ) }

  private

  def update_total_posts_count
    # update category total count column to show total posts count
    category.increment(:total_count, 1).save
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_account!, except: [:show]
  before_action :set_post, only: [:show, :edit, :update, :destroy, :save_post_view]
  before_action :can_modify_post, only: [:edit, :update, :destroy]

  # GET /posts
  def index
    @posts = Post.all
  end

  # GET /posts/1
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  def create
    @post = Post.new(post_params)
    @post.account_id = current_account.id

    if @post.save
      redirect_to @post, notice: 'Post was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /posts/1
  def update
    if @post.update(post_params)
      redirect_to @post, notice: 'Post was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /posts/1
  def destroy
    @post.destroy
    redirect_to posts_url, notice: 'Post was successfully destroyed.'
  end

  def save_post_view
    # increment view count for post
    @post.increment(:views, 1).save
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    def can_modify_post
      redirect_back(fallback_location: root_path) and return unless @post.account_id == current_account.id
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :summary, :body, :active, :category_id)
    end
end

app/controllers/public_controller.rb
class PublicController < ApplicationController

  def homepage
    @posts = Post.active.order_by_latest_first.limit_2
    @categories = Category.all
  end

  def about
  end

  def blog
  end

  def contact
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def page_title title
    content_for :page_title, title.to_s
  end

end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/posts_helper.rb
module PostsHelper

  def post_meta post
    "Created by #{ post.account.present? ? post.account.first_name : 'Admin' } #{ time_ago_in_words(post.created_at) } ago. Posted within #{ post.category.title } (#{ post.views } views)."
  end

end

app/views/layouts/_footer.html.erb
<div class="container bg-white">
  <div class="row">
    <div class="col" id="footer">
      <p>Copyright &copy; <%= Date.current.strftime("%Y") %> Rails Blog</p>
    </div>
  </div>
</div>

app/views/layouts/_form_validation.html.erb
<% if local_assigns[:item] && item.errors.any? %>
  <div id="error_explanation">
    <ul>
      <% item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_menu.html.erb
<h1 class="float-left" id="site-name">Rails Blog</h1>

<ul class="float-right list-unstyled" id="topnav">
  <li><%= link_to "Home", root_path %></li>
  <li><%= link_to "About", about_path %></li>
  <li><%= link_to "Blog", blog_path %></li>
  <li><%= link_to "Contact", contact_path %></li>
  <% if account_signed_in? %>
  <li><%= link_to "Sign Out", destroy_account_session_path, method: :delete %></li>
  <% else %>
  <li><%= link_to "Sign In", new_account_session_path %></li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for?(:page_title) ? yield(:page_title) : "Ruby on Rails Blog" %> | Rails App</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <div class="container bg-white">
      <div class="row">
        <div class="col page-nav">
          <%= render partial: "layouts/menu" %>
        </div>
      </div>
      <div class="row">
        <div class="col">
          <%= yield %>
        </div>
      </div>
    </div>

    <%= render partial: "layouts/footer" %>

    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

    <%= yield(:scripts) if content_for?(:scripts) %>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <%= render partial: "layouts/form_validation", locals: { item: post } %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :summary %>
    <%= form.text_field :summary %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <div class="field">
    <%= form.label :category_id %>
    <%= form.select :category_id, Category.all.collect{ |c| [c.title, c.id] } %>
  </div>

  <div class="field">
    <%= form.label :active %>
    <%= form.check_box :active %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<p class="h5"><%= link_to post.title, post_path(post) %></p>
<%= post_meta post %>
<p><%= post.summary %></p>

app/views/posts/_view_form.html.erb
<%= form_with(url: post_view_path, html: { id: "save_views" }) do |form| %>
  <%= form.hidden_field :id, value: post.id %>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Posts</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Summary</th>
      <th>Body</th>
      <th>Active</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= post.summary %></td>
        <td><%= post.body %></td>
        <td><%= post.active %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<h1><%= @post.title %></h1>
<p><small><%= post_meta @post %></small></p>

<%= simple_format @post.body %>

<%= render partial: "posts/view_form", locals: { post: @post } %>